    simulator_type: "Mujoco"
    robot_name: astribot_s1_whole_body
    model_path: "/astribot_descriptions/mjcf/astribot_s1_mjcf/astribot_s1_with_gripper.xml"
    robot_list: [
        "astribot_chassis",
        "astribot_torso",
        "astribot_head",
        "astribot_arm_left",
        "astribot_gripper_left",
        "astribot_arm_right",
        "astribot_gripper_right",
    ]
    joint_names_list: [
        ["astribot_chassis_x",
         "astribot_chassis_y",
         "astribot_chassis_zrot"],
        ["astribot_torso_joint_1",
         "astribot_torso_joint_2",
         "astribot_torso_joint_3",
         "astribot_torso_joint_4"],

        ["astribot_head_joint_1",
         "astribot_head_joint_2"],

        ["astribot_arm_left_joint_1",
         "astribot_arm_left_joint_2",
         "astribot_arm_left_joint_3",
         "astribot_arm_left_joint_4",
         "astribot_arm_left_joint_5",
         "astribot_arm_left_joint_6",
         "astribot_arm_left_joint_7",],
        ['astribot_gripper_left_joint_L1'],
        ["astribot_arm_right_joint_1",
         "astribot_arm_right_joint_2",
         "astribot_arm_right_joint_3",
         "astribot_arm_right_joint_4",
         "astribot_arm_right_joint_5",
         "astribot_arm_right_joint_6",
         "astribot_arm_right_joint_7",],
        ['astribot_gripper_right_joint_L1'],
    ]
    gravity_compensation: True
    mode: "human"
    width: 1920
    height: 1080
    object_names: []  #, "box_green", "box_blue"
    camera_names: []
    sensor_names: ['force_torque_sensor_left', 'force_torque_sensor_right', 'astribot_chassis_imu_site']
    vel_compensation_list: [False, True, True, True, True, True, True]
    update_trajectory_map: {}
