    simulator_type: "Maniskill"
    robot_name: astribot_whole_body
    model_path: "/astribot_descriptions/urdf/astribot_s1_urdf/astribot_whole_body_maniskill.urdf"
    robot_list: [
        "astribot_torso",
        "astribot_head",
        "astribot_arm_left",
        "astribot_gripper_left",
        "astribot_arm_right",
        "astribot_gripper_right",
    ]
    joint_names_list: [
        ["astribot_torso_joint_1",
         "astribot_torso_joint_2",
         "astribot_torso_joint_3",
         "astribot_torso_joint_4"],
        ["astribot_head_joint_1",
         "astribot_head_joint_2"],
        ["astribot_arm_left_joint_1",
         "astribot_arm_left_joint_2",
         "astribot_arm_left_joint_3",
         "astribot_arm_left_joint_4",
         "astribot_arm_left_joint_5",
         "astribot_arm_left_joint_6",
         "astribot_arm_left_joint_7",],
        ['astribot_gripper_left_joint_L1',
        'astribot_gripper_left_joint_L2',
        'astribot_gripper_left_joint_L11',
        'astribot_gripper_left_joint_R1',
        'astribot_gripper_left_joint_R2',
        'astribot_gripper_left_joint_R11'],
        ["astribot_arm_right_joint_1",
         "astribot_arm_right_joint_2",
         "astribot_arm_right_joint_3",
         "astribot_arm_right_joint_4",
         "astribot_arm_right_joint_5",
         "astribot_arm_right_joint_6",
         "astribot_arm_right_joint_7",],
        ['astribot_gripper_right_joint_L1',
        'astribot_gripper_right_joint_L2',
        'astribot_gripper_right_joint_L11',
        'astribot_gripper_right_joint_R1',
        'astribot_gripper_right_joint_R2',
        'astribot_gripper_right_joint_R11'],
    ]
    gravity_compensation: True
    mode: "human"
    width: 1920
    height: 1080
    object_names: []
    camera_names: ["astribot_arm_right_effector", "astribot_arm_left_effector", "astribot_head"]
    sensor_names: []
    vel_compensation_list: [False, True, True, True, True, True, True]